/** Identifier for distinguishing among entity classes and tracing configuration
    selection. */
export enum EntityType {
  FRUIT = 'Fruit',
  APPLE_TREE = 'AppleTree',
  ITEM = 'Item',
  BACKPACKER = 'Backpacker',
  BEE = 'Bee',
  BUNNY = 'Bunny',
  FLY = 'Fly',
  FLOWER = 'Flower',
  FROG = 'Frog',
  PIG = 'Pig',
  SNAKE = 'Snake',
  GROUP = 'Group',
  LEVEL_EDITOR_SANDBOX = 'LevelEditorSandbox',
  BUSH = 'Bush',
  CATTAILS = 'Cattails',
  CLOUD = 'Cloud',
  CLOVER = 'Clover',
  COMPARTMENT = 'Compartment',
  CONIFER = 'Conifer',
  FLAG = 'Flag',
  GRASS = 'Grass',
  MONUMENT = 'Monument',
  MOUNTAIN = 'Mountain',
  PATH = 'Path',
  PLANE = 'Plane',
  POND = 'Pond',
  SUBSHRUB = 'Subshrub',
  TREE = 'Tree',
  UI_BUTTON = 'uiButton',
  LIFE_COUNTER = 'LifeCounter',
  NINE_PATCH = 'NinePatch',
  PLAYER_STATUS = 'PlayerStatus',
  UI_CHECKBOX = 'uiCheckbox',
  UI_CURSOR = 'uiCursor',
  UI_CURSOR_DOT = 'uiCursorDot',
  UI_CURSOR_HAND = 'uiCursorHand',
  UI_CURSOR_RETICLE = 'uiCursorReticle',
  UI_DATE_VERSION_HASH = 'uiDateVersionHash',
  UI_DESTINATION_MARKER = 'uiDestinationMarker',
  UI_ENTITY_PICKER = 'uiEntityPicker',
  UI_LEVEL_EDITOR_MENU = 'uiLevelEditorMenu',
  UI_LEVEL_EDITOR_PANEL = 'uiLevelEditorPanel',
  UI_LEVEL_EDITOR_PANEL_BACKGROUND = 'uiLevelEditorPanelBackground',
  UI_LEVEL_LINK = 'uiLevelLink',
  UI_MARQUEE = 'uiMarquee',
  UI_RADIO_CHECKBOX_GROUP = 'uiRadioCheckboxGroup',
  UI_TEXT = 'uiText',
  UI_TOOLBAR = 'uiToolbar'
}

export const UI_KEY_PREFIX = 'UI_'
