/** Identifier for distinguishing among entity classes and tracing configuration
    selection. */
export enum EntityType {
  BACKPACKER = 'backpacker',
  BEE = 'bee',
  BUNNY = 'bunny',
  FLY = 'fly',
  FROG = 'frog',
  SNAKE = 'snake',
  GROUP = 'group',
  LEVEL_EDITOR_SANDBOX = 'levelEditorSandbox',
  BUSH = 'bush',
  CATTAILS = 'cattails',
  CLOUD = 'cloud',
  CLOVER = 'clover',
  CONIFER = 'conifer',
  FLAG = 'flag',
  GRASS = 'grass',
  ISO_GRASS = 'isoGrass',
  MOUNTAIN = 'mountain',
  PATH = 'path',
  PLANE = 'plane',
  POND = 'pond',
  PYRAMID = 'pyramid',
  SUBSHRUB = 'subshrub',
  TREE = 'tree',
  UI_BUTTON = 'uiButton',
  UI_CHECKBOX = 'uiCheckbox',
  UI_CURSOR = 'uiCursor',
  UI_DATE_VERSION_HASH = 'uiDateVersionHash',
  UI_DESTINATION_MARKER = 'uiDestinationMarker',
  UI_ENTITY_PICKER = 'uiEntityPicker',
  UI_LEVEL_EDITOR_MENU = 'uiLevelEditorMenu',
  UI_LEVEL_EDITOR_PANEL = 'uiLevelEditorPanel',
  UI_LEVEL_EDITOR_PANEL_BACKGROUND = 'uiLevelEditorPanelBackground',
  UI_LEVEL_LINK = 'uiLevelLink',
  UI_MARQUEE = 'uiMarquee',
  UI_RADIO_CHECKBOX_GROUP = 'uiRadioCheckboxGroup',
  UI_TEXT = 'uiText',
  UI_TOOLBAR = 'uiToolbar'
}

export const UI_KEY_PREFIX = 'UI_'
