/** Identifier for distinguishing among entity classes and tracing configuration
    selection. */
export enum EntityType {
  FRUIT = 'fruit',
  APPLE_TREE = 'appleTree',
  ITEM = 'item',
  BACKPACKER = 'backpacker',
  BEE = 'bee',
  BUNNY = 'bunny',
  FLY = 'fly',
  FLOWER = 'flower',
  FROG = 'frog',
  PIG = 'pig',
  SNAKE = 'snake',
  GROUP = 'group',
  LEVEL_EDITOR_SANDBOX = 'levelEditorSandbox',
  BUSH = 'bush',
  CATTAILS = 'cattails',
  CLOUD = 'cloud',
  CLOVER = 'clover',
  COMPARTMENT = 'compartment',
  CONIFER = 'conifer',
  FLAG = 'flag',
  GRASS = 'grass',
  MONUMENT = 'monument',
  MOUNTAIN = 'mountain',
  PATH = 'path',
  PLANE = 'plane',
  POND = 'pond',
  SUBSHRUB = 'subshrub',
  TREE = 'tree',
  UI_BUTTON = 'uiButton',
  LIFE_COUNTER = 'lifeCounter',
  PLAYER_STATUS = 'backpackerIcon',
  UI_CHECKBOX = 'uiCheckbox',
  UI_CURSOR = 'uiCursor',
  UI_CURSOR_DOT = 'uiCursorDot',
  UI_CURSOR_HAND = 'uiCursorHand',
  UI_CURSOR_RETICLE = 'uiCursorReticle',
  UI_DATE_VERSION_HASH = 'uiDateVersionHash',
  UI_DESTINATION_MARKER = 'uiDestinationMarker',
  UI_ENTITY_PICKER = 'uiEntityPicker',
  UI_LEVEL_EDITOR_MENU = 'uiLevelEditorMenu',
  UI_LEVEL_EDITOR_PANEL = 'uiLevelEditorPanel',
  UI_LEVEL_EDITOR_PANEL_BACKGROUND = 'uiLevelEditorPanelBackground',
  UI_LEVEL_LINK = 'uiLevelLink',
  UI_MARQUEE = 'uiMarquee',
  UI_RADIO_CHECKBOX_GROUP = 'uiRadioCheckboxGroup',
  UI_TEXT = 'uiText',
  UI_TOOLBAR = 'uiToolbar'
}

export const UI_KEY_PREFIX = 'UI_'
